apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdb-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imdb-api
  template:
    metadata:
      labels:
        app: imdb-api
    spec:
      containers:
        - name: imdb-api
          image: venkatesh2007567/imdb-rating-api:latest
          ports:
            - containerPort: 8000
